### ISSUE TITLE
Property has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by koftaylov** [aturlov/colorpicker4angular#12]
Property '_colorPicker3' has no initializer and is not definitely assigned in the constructor.

private _colorPicker3?: AptColorPickerComponent;

**Comment by aturlov** [comment]
Use declaration like this and the problem is solved:
`private _colorPicker3: AptColorPickerComponent | null = null;`

**Comment by aturlov** [comment]
To understand this syntax refer to TypeScript "Types as Set" explanation https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-oop.html#types-as-sets

**Comment by koftaylov** [comment]
Thanks for the link.
It's mind-blowing conception.
