### ISSUE TITLE
Develop unit tests

### ISSUE THREAD

**Issue by koftaylov** [aturlov/colorpicker4angular#26]
Find out what unit tests should exist
Develop the unit tests

**Comment by aturlov** [comment]
Some good reading on Angular testing:
https://angular.io/guide/testing#more-info-on-testing

**Comment by koftaylov** [comment]
@aturlov 
it's possible to use just console.log() from the tests. it works well.

**Comment by koftaylov** [comment]
counter "toHaveBeenCalledTimes" counts callings for the whole test suite
